Margo\MargoBundle\Entity\Classe:
  type: entity
  table: classe
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    etudiants:
      targetEntity: Etudiant
      mappedBy: classe
  manyToOne:
    filiere:
      targetEntity: Filiere
      inversedBy: classes
      joinColumn:
        name: id_filiere
        referencedColumnName: id
  manyToMany:
    intervenants:
      targetEntity: Intervenant
      joinTable:
        name: classe_intervenant
        joinColumns:
          id_classe:
            referencedColumnName: id
        inverseJoinColumns:
          id_intervenant:
            referencedColumnName: id