Margo\MargoBundle\Entity\Etudiant:
  type: entity
  table: etudiant
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    birthdate:
      type: datetime
      nullable: false
  manyToOne:
    classe:
      targetEntity: Classe
      inversedBy: etudiants
      joinColumn:
        name: id_classe
        referencedColumnName: id