Margo\MargoBundle\Entity\Etudiant:
  type: entity
  table: etudiant
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nom:
      type: string
      length: 500
      nullable: false
    prenom:
      type: string
      length: 500
      nullable: false
    situation:
      type: string
      length: 50
      nullable: false
    adresse:
      type: string
      length: 1000
      nullable: false
  manyToOne:
    classe:
      targetEntity: Classe
      inversedBy: etudiants
      joinColumn:
        name: id_classe
        referencedColumnName: id