Margo\MargoBundle\Entity\Filiere:
  type: entity
  table: filiere
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 500
      nullable: false
  oneToMany:
    classes:
      targetEntity: Classe
      mappedBy: filiere
    intervenants:
      targetEntity: Intervenant
      mappedBy: filiere
    matieres:
      targetEntity: Matiere
      mappedBy: filiere