Margo\MargoBundle\Entity\Intervenant:
  type: entity
  table: intervenant
  inheritanceType: JOINED
  discriminatorColumn:
    name: type
    type: string
    length: 255
  discriminatorMap:
    enseignant: Enseignant
    Technicien: Technicien
  fields:
    is_permanent:
      type: boolean
      nullable: true
  manyToMany:
    matieres:
      targetEntity: Matiere
      mappedBy: intervenants
    classes:
      targetEntity: Classe
      mappedBy: intervenants